version: "3.8"

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:?}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - ${DB_PORT:-5432}:5432
    expose:
      - 5432
    volumes:
      - database_data:/var/lib/postgresql/data
    secrets:
      - db_password

secrets:
  db_password:
    file: .secrets/db_password

volumes:
  database_data: