version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    env_file: .env.prod
    ports:
      - ${PORT:-80}:80
    expose:
      - 80
    secrets:
      - db_url

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:?}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:5432
    expose:
      - 5432
    secrets:
      - db_password

volumes:
  database_data:

secrets:
  db_password:
    file: .secrets/db_password
  db_url:
    file: .secrets/db_url
