apiVersion: v1
kind: PersistentVolume
metadata:
  name: pics-server-db-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/pgsql/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pics-server-db-pvc
  labels:
    app: pics-server-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
